const EErrors = {
  INCOMPLETE_DATA: 1,
  DUPLICATE_CODE: 2,
  INVALID_TYPES: 3,
  ID_NOT_FOUND: 4,
  INSUFFICIENT_STOCK: 5,
  CART_EMPTY: 6,
  CART_NOT_FOUND: 7,
  NOT_PRODUCT_IN_THE_CART: 8,
  NON_EXISTENT_PRODUCT: 9,
  DOCUMENT_ALREADY_LOADED: 10,
  NOT_ADD_PRODUCT:11,
};
export default EErrors;