const  EErrors = {
    INCOMPLETE_DATA:1,
    DUPLICATE_CODE:2,
    INVALID_TYPES:3,
    ID_NOT_FOUND:4,
    INSUFFICIENT_STOCK:5,
    CART_EMPTY:6,
    CART_NOT_FOUND:7,
    NOT_PRODUCT_IN_THE_CART:8

}
export default EErrors;